### ISSUE TITLE
Please add the new maxLineLength parameter

### ISSUE THREAD

**Issue by german-rios-gonzalez** [postcasio/atom-grammar-token-limit#2]
Hi, first of all thank you for this package, but after the release of atom v1.15 there is a new limit this time in the length of the line, and after the release of atom v1.16 this parameter can be configured just like you did with maxTokensPerLine, so please add this new parameter to your package.

**Comment by Swoy** [comment]
could you provide the new parameter, and we can fix it :)

**Comment by Gorislim13** [comment]
@Swoy
